import type { AffiliateProduct, BlogPost, Category, Site } from "./types"

export const demoSite: Site = {
  id: "site_demo",
  name: "Pop Deals",
  domain: "localhost",
  aliasDomains: [],
  locale: "en-US",
  country: "US",
  currency: "USD",
  description:
    "Hand-picked marketplace deals, coupons, and shopping guides for affiliate SEO websites.",
  logoUrl: null,
  themeColor: "#c83d2d",
  seoTitle: "Pop Deals",
  seoDescription:
    "Hand-picked marketplace deals, coupons, and shopping guides.",
}

export const demoCategories: Category[] = [
  {
    id: "cat_gadgets",
    siteId: demoSite.id,
    parentId: null,
    navSection: "categories",
    name: "Gadgets",
    slug: "gadgets",
    description: "Useful tech accessories and small electronics.",
    sortOrder: 10,
  },
  {
    id: "cat_tiktok",
    siteId: demoSite.id,
    parentId: null,
    navSection: "coupons",
    name: "TikTok Shop",
    slug: "tiktok-shop",
    description: "Coupons and creator-driven marketplace picks.",
    sortOrder: 20,
  },
  {
    id: "cat_travel",
    siteId: demoSite.id,
    parentId: null,
    navSection: "travel",
    name: "Travel Essentials",
    slug: "travel-essentials",
    description: "Bags, organizers, and travel-friendly deals.",
    sortOrder: 30,
  },
  {
    id: "cat_gaming",
    siteId: demoSite.id,
    parentId: null,
    navSection: "gaming",
    name: "Gaming Gear",
    slug: "gaming-gear",
    description: "Controllers, headsets, keyboards, and desk upgrades.",
    sortOrder: 40,
  },
]

export const demoProducts: AffiliateProduct[] = [
  {
    id: "prod_metrobeans",
    siteId: demoSite.id,
    categoryId: "cat_tiktok",
    title: "SPRINGHOUSE Metrobeans Blind Box Plush Bag Charm",
    slug: "springhouse-metrobeans-blind-box-plush-bag-charm",
    description:
      "A compact collectible charm suitable for TikTok Shop creator campaigns and playful gift guides.",
    imageUrl: null,
    platform: "tiktok_shop",
    platformTitle: "TikTok Shop",
    country: "MY",
    priceText: "$8.99",
    affiliateUrl: "https://example.com/affiliate/tiktok",
    affiliateId: "demo-affiliate",
    accountUser: "demo-account",
    creatorUsername: "",
    status: "published",
    viewCount: 1280,
    clickCount: 214,
  },
  {
    id: "prod_keyboard",
    siteId: demoSite.id,
    categoryId: "cat_gaming",
    title: "Compact RGB Mechanical Keyboard Deal",
    slug: "compact-rgb-mechanical-keyboard-deal",
    description:
      "A gaming accessory offer prepared for comparison pages and weekly roundup posts.",
    imageUrl: null,
    platform: "aliexpress",
    platformTitle: "AliExpress",
    country: "US",
    priceText: "$24.50",
    affiliateUrl: "https://example.com/affiliate/aliexpress",
    affiliateId: "demo-affiliate",
    accountUser: "demo-account",
    creatorUsername: null,
    status: "published",
    viewCount: 940,
    clickCount: 166,
  },
  {
    id: "prod_travel_pouch",
    siteId: demoSite.id,
    categoryId: "cat_travel",
    title: "Waterproof Travel Cable Organizer",
    slug: "waterproof-travel-cable-organizer",
    description:
      "A practical low-ticket product for travel listicles, packing guides, and coupon pages.",
    imageUrl: null,
    platform: "shopee",
    platformTitle: "Shopee",
    country: "SG",
    priceText: "$5.20",
    affiliateUrl: "https://example.com/affiliate/shopee",
    affiliateId: "demo-affiliate",
    accountUser: "demo-account",
    creatorUsername: null,
    status: "published",
    viewCount: 702,
    clickCount: 91,
  },
]

export const demoPosts: BlogPost[] = [
  {
    id: "post_tiktok_shop",
    siteId: demoSite.id,
    title: "How to Find TikTok Shop Deals Worth Sharing",
    slug: "how-to-find-tiktok-shop-deals-worth-sharing",
    excerpt:
      "A short guide structure for creator-led affiliate campaigns and weekly marketplace picks.",
    body: "TikTok Shop affiliate pages work best when the product selection is focused, current, and connected to creators or content themes.",
    status: "published",
    seoTitle: "How to Find TikTok Shop Deals Worth Sharing",
    seoDescription:
      "Build stronger TikTok Shop affiliate pages with focused product picks and creator-led deal themes.",
    sourceTitle: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: "Original",
    sourceLicenseUrl: null,
    publishedAt: "2026-06-07T00:00:00.000Z",
  },
  {
    id: "post_budget_gaming",
    siteId: demoSite.id,
    title: "Best Budget Gaming Accessories for Deal Pages",
    slug: "best-budget-gaming-accessories-for-deal-pages",
    excerpt:
      "Use gaming categories to build SEO pages around keyboards, headsets, controllers, and desk gear.",
    body: "Gaming affiliate content should group deals by use case, platform, and budget instead of only listing random discounts.",
    status: "published",
    seoTitle: "Best Budget Gaming Accessories for Deal Pages",
    seoDescription:
      "Plan SEO-friendly gaming accessory deal pages around use case, platform, and budget.",
    sourceTitle: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: "Original",
    sourceLicenseUrl: null,
    publishedAt: "2026-06-07T00:00:00.000Z",
  },
]
